### ISSUE TITLE
Feature suggestion:  Some views shouldn't resize when whole thing resizes

### ISSUE THREAD

**Issue by sgehrman** [caduandrade/multi_split_view#6] opened 2021-09-02 08:06 UTC
I have a sidebar on the right and left and a view in the middle.  

When I resize the window, I only want the middle view to grow or shrink.  The other views must be manually resized.

I also want to specify that the sidebar has  a default width in pixels that can resize beyond that if the user drags it.  

I know NSSplitView from Cocoa handles cases like this, but I haven't looked at it in years.

Also you should have a reasonable default divider painter.  Everyone is going to want a decent default.  See split_view, they have some grab handles by default that are nice.  I just want to set the divider color and a mouse over color, and the default painter can redraw when I move the mouse over it.

Writing a full featured split view is actually pretty difficult, so be sure your ready for some pain if you plan on updating it to do all this.  I made one years ago.

**Comment by caduandrade** [comment] 2021-09-02 13:11
By design decision, sizes are defined by weights to avoid problems with window resizing. Fixing the size in pixels or turning off auto-resizing are acceptable use cases, but I would need to give some thought to what the rule would be when there is not enough space for areas with "fixed" pixels. Maybe decrease all these areas equally in the case when setting the pixels. And in the case where only the automatic resizing is turned off, reduce it respecting the weight.

**Comment by caduandrade** [comment] 2021-09-02 13:23
Thanks for the suggestions!

**Comment by caduandrade** [comment] 2021-09-27 20:38
Issue to improve the dividers: #9

**Comment by caduandrade** [comment] 2024-03-09 16:16
Will be resolved by #54

**Closed** 2024-04-29 18:51 UTC
Labels: enhancement
